### ISSUE TITLE
Ngrok

### ISSUE THREAD

**Issue by peterhuang-7189** [thewickedkarma/blackeye-im#47]
Download error...
![截圖 2022-02-06 下午10 36 16](https://user-images.githubusercontent.com/86280010/152685982-f857920e-228a-48b8-99ea-49033ce58c28.png)

**Comment by thewickedkarma** [comment]
Might be the problem with your internet connection.

Alternatively, you can do this:
```
cd blackeye-im
sudo apt install wget 
wget https://bin.equinox.io/c/4VmDzA7iaHb/ngrok-stable-linux-arm.tgz 
#Here, in the link, replace arm by your architecture i.e 'arm' or  'arm64' or 'amd64' based on your device arch
tar xvzf *.tgz 
```

Then run blackeye.sh
