### ISSUE TITLE
command not found

### ISSUE THREAD

**Issue by mowgly11** [thewickedkarma/blackeye-im#82]
when i try to run the server with ngrok i get this annoying err
![unknown](https://user-images.githubusercontent.com/83482871/186947711-ae19f8f8-26ef-4183-8de7-3b877ce96d5d.png)

**Comment by Davidalfa081** [comment]
I have fix it....

Generate link successful

**Comment by avshiva-noro** [comment]
install jq and xsel, sudo apt install jq xsel
